# Generated by Django 4.1.4 on 2022-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeeklySales', '0002_alter_weeklysale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysale',
            name='image',
            field=models.ImageField(blank=True, upload_to='./images/weekly_sale'),
        ),
    ]
