# Generated by Django 4.1.4 on 2023-01-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_remove_product_wishlist'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wished_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Products.product'),
        ),
    ]
