# Generated by Django 4.1.4 on 2023-01-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_remove_product_wishlist'),
        ('wishlist', '0005_remove_wishlist_wished_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wished_item',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='Products.product'),
            preserve_default=False,
        ),
    ]
