# Generated by Django 4.1.4 on 2023-01-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_wishlist_wished_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_item',
        ),
    ]
