# Generated by Django 4.1.4 on 2023-01-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_remove_product_wishlist'),
        ('wishlist', '0007_remove_wishlist_wished_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wished_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='Products.product'),
        ),
    ]
