# Generated by Django 4.1.4 on 2022-12-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0002_brandcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='./images/brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='./images/brand'),
        ),
        migrations.AddField(
            model_name='brandcategories',
            name='brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Brands.brand'),
        ),
        migrations.AddField(
            model_name='brandcategories',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
