# Generated by Django 4.1.4 on 2022-12-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0003_brand_description_brand_image_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcategories',
            name='brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Brands.brand'),
        ),
    ]
