# Generated by Django 4.1.4 on 2022-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0004_alter_brandcategories_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='./brand'),
        ),
    ]
