# Generated by Django 4.1.4 on 2022-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0005_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='./brand'),
        ),
    ]
