# Generated by Django 4.1.4 on 2022-12-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0006_alter_brand_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='brand'),
        ),
    ]
