# Generated by Django 4.1.4 on 2022-12-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
