# Generated by Django 4.1.4 on 2023-01-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_wishlist_wished_item'),
        ('News', '0003_alter_news_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_product', to='wishlist.wishlist')),
            ],
        ),
    ]
