# Generated by Django 4.1.4 on 2023-01-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_wishlistproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistProduct',
        ),
    ]
