# Generated by Django 4.1.4 on 2023-01-13 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='legal_address',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='physical_address',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
