# Generated by Django 4.1.4 on 2023-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_useraccount_birth_useraccount_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(null=True, upload_to='./user'),
        ),
    ]
