# Generated by Django 4.1.4 on 2023-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_useraccount_birth_alter_useraccount_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birth',
            field=models.DateField(blank=True, default='timezone.now'),
        ),
    ]
