# Generated by Django 4.1.4 on 2023-01-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_useraccount_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='birth',
            new_name='birth_day',
        ),
    ]
