# Generated by Django 4.1.4 on 2023-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_rename_birth_useraccount_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='avatar',
            field=models.ImageField(blank=True, default='./user/img_avatar.png', upload_to='./user'),
        ),
    ]
