# Generated by Django 4.1.4 on 2023-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_alter_useraccount_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='physical_address',
        ),
    ]
