# Generated by Django 4.1.4 on 2023-01-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_useraccount_avatar_useraccount_birth_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='physical_address',
        ),
    ]
