# Generated by Django 4.1.4 on 2022-12-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='BranchWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.TextField()),
                ('hour', models.TextField()),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='Branch.branch')),
            ],
        ),
    ]
