# Generated by Django 4.1.4 on 2022-12-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0002_branch_phone_branchworkinghours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchworkinghours',
            old_name='working_hours',
            new_name='branch',
        ),
    ]
