# Generated by Django 4.1.4 on 2022-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_rename_working_hours_branchworkinghours_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcoord',
            name='lat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='branchcoord',
            name='long',
            field=models.TextField(),
        ),
    ]
