# Generated by Django 4.1.4 on 2022-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_alter_branchcoord_lat_alter_branchcoord_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchcoord',
            name='lat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='branchcoord',
            name='long',
            field=models.CharField(max_length=200),
        ),
    ]
