# Generated by Django 4.1.4 on 2022-12-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0005_alter_branchcoord_lat_alter_branchcoord_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
