# Generated by Django 4.1.4 on 2022-12-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0007_alter_branchworkinghours_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchworkinghours',
            name='hour',
            field=models.CharField(max_length=200),
        ),
    ]
