# Generated by Django 4.1.4 on 2022-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0008_alter_branchworkinghours_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
