# Generated by Django 4.1.4 on 2022-12-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Brands', '0004_alter_brandcategories_brands'),
        ('Branch', '0006_alter_branch_phone'),
        ('Products', '0002_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('separate', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.ImageField(null=True, upload_to='./images/products')),
                ('amount', models.IntegerField()),
                ('new', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField(default=models.IntegerField())),
                ('sale', models.IntegerField(blank=True, default=0)),
                ('new_price', models.IntegerField(blank=True, default=0)),
                ('total_new_price', models.IntegerField(blank=True, default=models.IntegerField(blank=True, default=0))),
                ('deadline', models.TimeField(null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('product_model', models.CharField(max_length=200, null=True)),
                ('top', models.BooleanField(blank=True, default=False)),
                ('popularity', models.BooleanField(blank=True, default=False)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Brands.brandcategories')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationBasics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('middle', models.CharField(max_length=200, null=True)),
                ('basic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='Products.specifications')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='./images/products')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='Products.product')),
            ],
        ),
    ]
