# Generated by Django 4.1.4 on 2022-12-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
