# Generated by Django 4.1.4 on 2022-12-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(default=models.IntegerField(null=True)),
        ),
    ]
