# Generated by Django 4.1.4 on 2022-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_product_total_new_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='./products'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(null=True, upload_to='./products'),
        ),
    ]
