# Generated by Django 4.1.4 on 2022-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_product_created_at_product_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
