# Generated by Django 4.1.4 on 2022-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_product_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deadline',
            field=models.DateField(blank=True, default='2099-10-10', null=True),
        ),
    ]
