# Generated by Django 4.1.4 on 2023-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_in_stock',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
