# Generated by Django 4.1.4 on 2023-01-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_product_total_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbranch',
            old_name='branch',
            new_name='branch_in_stock',
        ),
    ]
