# Generated by Django 4.1.4 on 2023-01-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_rename_branch_productbranch_branch_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbranch',
            old_name='branch_in_stock',
            new_name='branch',
        ),
    ]
